basePath: /
consumes:
- application/json
definitions:
  Item:
    description: Items defines the structure of an API item
    properties:
      Id:
        format: int64
        type: integer
      Name:
        type: string
    type: object
    x-go-package: github.com/aditya109/go-server-template/internal/models
info:
  description: Documentation of crud-template API
  title: http API
  version: 1.0.0
paths:
  /:
    get:
      description: Returns a welcome message
      operationId: welcome
      responses:
        "200":
          $ref: '#/responses/WelcomeResponse'
      tags:
      - home
  /item/{id}:
    get:
      description: Returns an item with id from the existing list of items
      operationId: listItem
      responses:
        "200":
          $ref: '#/responses/GetItemWithIdReponse'
      tags:
      - item
  /items:
    get:
      description: Returns a list of items, no query params required
      operationId: listItems
      responses:
        "200":
          $ref: '#/responses/SimpleGetItemsResponse'
      tags:
      - items
  /items?id=12&name=Bertine:
    get:
      description: Returns items filtered by query parameters from the existing list
        of items
      operationId: listItems
      responses:
        "200":
          $ref: '#/responses/GetWithQueryParamsReponse'
      tags:
      - items
produces:
- application/json
responses:
  GetItemWithIdResponse:
    description: An item returned in response
    schema:
      $ref: '#/definitions/Item'
  GetItemWithQueryParamResponse:
    description: An item returned in response
    schema:
      items:
        $ref: '#/definitions/Item'
      type: array
  SimpleGetItemsResponse:
    description: A list of items returned in the response
    schema:
      items:
        $ref: '#/definitions/Item'
      type: array
  WelcomeResponse:
    description: A welcome response shown on / URL
    schema:
      type: string
schemes:
- http
swagger: "2.0"
