server:
  environment: "dev" # pre-configured values- prod, dev, stag
  ports:
  - name: "http-port"
    port: 7979
  - name: "redis-port"
    port: 8080
  endpoints: 
  - name: "localhost"
    tlsEnabled: false
    envType: "dev" # must have same (case-sensitive) values as configured `environment` field values
  timeouts:
  - name: "write-timeout"
    value: 15     # assumed value in seconds
  - name: "read-timeout"
    value: 15     # assumed value in seconds
        
        

